apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
  namespace: evgenii-subbotin-ikbo0119
spec:
  containers:
    - name: memory-demo-ctr-3
      image: polinux/stress
      resources:
        limits:
          memory: "1000Gi"
        requests:
          memory: "1000Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
